nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://www.fragrantica.pl', 'https://www.fragrantica.com']
        allow_methods: ['GET']
        allow_headers: ['Content-Type']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
