search:
    path: /search/{provider}/{name}
    controller: App\Controller\SearchAction
    requirements: 
        provider: perfumehub.pl|example.com
        name: ".+"
proxy:
    path: /proxy/{provider}/{path}
    controller: App\Controller\ProxyAction
    requirements: 
        provider: perfumehub.pl|example.com
price_history:
    path: /price-history/{provider}
    controller: App\Controller\PriceHistoryAction
    requirements:
        provider: perfumehub.pl|example.com
report_link:
    path: /report-link/{provider}
    controller: App\Controller\ReportLinkAction
    requirements:
        provider: perfumehub.pl|example.com
